import type { AnamneseFormValues } from "./schema"

export const VALORES_INICIAIS: AnamneseFormValues = {
  dadosPessoais: {
    nome: "",
    dataNascimento: "",
    idade: "" as unknown as number,
    sexo: undefined as unknown as "feminino",
    profissao: "",
    cargaHoraria: "",
    contato: "",
    encaminhadoPor: "",
  },
  queixa: {
    motivoConsulta: "",
    objetivoConsulta: "",
    metaPrazo: "",
  },
  historicoClinico: {
    doencasDiagnosticadas: "",
    medicamentosContinuos: "",
    cirurgias: "",
    alergiasIntolerancias: "",
    historicoFamiliar: "",
    temExamesRecentes: undefined,
    sintomasGastrointestinais: "",
    cicloRegular: undefined,
    anticoncepcional: "",
    gestante: undefined,
    lactante: undefined,
    menopausa: undefined,
  },
  antropometria: {
    peso: "" as unknown as number,
    pesoHabitual: "",
    altura: "" as unknown as number,
    pesoMeta: "",
    circunferenciaCintura: "",
    circunferenciaQuadril: "",
    circunferenciaBraco: "",
    circunferenciaPanturrilha: "",
    gordura: "",
    massaMagra: "",
  },
  atividadeFisica: {
    nivelAtividade: undefined as unknown as "sedentario",
    praticaAtividade: undefined,
    atividadesQuais: "",
    frequenciaSemanal: "",
    duracaoSessao: "",
    intensidade: "",
    tempoPratica: "",
    perfilTrabalho: "",
  },
  estilo: {
    horasSono: "",
    qualidadeSono: "",
    nivelEstresse: "",
    consumoAgua: "",
    consumeAlcool: undefined,
    frequenciaAlcool: "",
    fumante: undefined,
    detalheTabagismo: "",
    habitosIntestinais: [],
    observacoes: "",
  },
  historicoAlimentar: {
    refeicoesDia: "",
    preferencias: [],
    aversoes: [],
    alergias: "",
    suplementos: [],
    suplementosDetalhes: "",
    recordatorio24h: [],
    observacoes: "",
  },
  frequenciaAlimentar: {},
  objetivos: {
    biotipo: undefined as unknown as "ectomorfo",
    objetivoComposicao: undefined as unknown as "emagrecer",
    objetivosPerformance: [],
    formula: "recomendada",
    observacoes: "",
  },
}
